[phases.setup]
nixPkgs = ["python3", "pip", "postgresql", "build-essential", "libpq-dev"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput --settings=settings_production",
    "python manage.py migrate --settings=settings_production"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 3 --timeout 120 settings_production.wsgi:application"
